# Generated by Django 4.0.4 on 2022-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_bio_alter_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/no-profile.png', upload_to='profiles/'),
        ),
    ]
