# Generated by Django 4.0.4 on 2022-04-28 13:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSkills',
            new_name='UserSkill',
        ),
    ]
