# Generated by Django 4.0.4 on 2022-04-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_userskills_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='finish_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='start_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userjob',
            name='finish_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userjob',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userjob',
            name='start_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
