# Generated by Django 4.0.4 on 2022-04-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usereducation_finish_year_usereducation_is_finished_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereducation',
            old_name='is_finished',
            new_name='still_going',
        ),
    ]
