# Generated by Django 4.0.4 on 2022-04-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_is_finished_usereducation_still_going'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjob',
            old_name='is_finished',
            new_name='still_going',
        ),
    ]
